### PR TITLE
Repro for issue #549

### PR DESCRIPTION
**Pull request by mckelveygreg**
Block in object field `Type instantiation is excessively deep and possibly infinite`

### CODE REVIEW

**Comment by saiichihashimoto** [comment]
I'm looking into this but let me ask you this: if you `ts-ignore` this error for the time being, does the updated `@sanity-typed/zod` zod schema give you the correct parser? Hopefully we can get ahead of the whack-a-mole of issues with this.

**Comment by saiichihashimoto** [comment]
I think I have a solve!

**Comment by saiichihashimoto** [comment]
Portable Text is amazing, but it's been the bane of my typing existence lol

**Comment by mckelveygreg** [comment]
Uh oh, i hope i didn't mess it up with merging main in?

**Comment by saiichihashimoto** [comment]
You're good! Good news is that the fix for this got rid of a _lot_ of `@ts-expect-error`s so #335 is also getting some help.

**Pull request merged**
