### PR TITLE
Renaming ref as namedType and then deprecating ref

### PR DESCRIPTION
**Pull request by cereallarceny**
- [x] Renamed `ref` to `namedType`
- [x] Aliased `ref` to `namedType`
- [x] Deprecated `ref`

The following PR simply swaps out the naming of `ref` to instead be called `namedType` and deprecates the old method name accordingly.

### CODE REVIEW

**Review by saiichihashimoto — CHANGES_REQUESTED** [review]
Amazing! Thank you for getting to this.

Can you replace the documentation as well? Then this'll be good to merge.

https://github.com/saiichihashimoto/sanity-typed/blob/main/packages/schema-builder/README.md#object-named

**Comment by saiichihashimoto** [comment]
> > Amazing! Thank you for getting to this.
> > Can you replace the documentation as well? Then this'll be good to merge.
> > https://github.com/saiichihashimoto/sanity-typed/blob/main/packages/schema-builder/README.md#object-named
> 
> I believe I already did @saiichihashimoto : https://github.com/saiichihashimoto/sanity-typed/pull/43/files#diff-f8ba4160c6d7f62bc6529c066613045813cb6cb1fb03181af888b5d662abf46bR818
> 
> Is that what you're referring to or is there another spot I missed?

no, I just can't read. Approved!

**Review by saiichihashimoto — APPROVED** [review]

**Review by saiichihashimoto — CHANGES_REQUESTED** [review]
Oh! One more thing.

I'm using [`semantic-release`](https://github.com/semantic-release/semantic-release) for deployments, which means it uses the commit messages to identify when to deploy. As it currently is, this won't deploy until something else happens to kick it off. Can you rebase and change the commit message to something along the lines of:

`fix(object): renaming ref() to namedType()`

**Comment by cereallarceny** [comment]
Hey @saiichihashimoto, so I've tried to do this, but I'm being told that Husky has a pre-rebase hook that catching and preventing me from doing so. Furthermore, it's also not a great idea to rebase pushed commits. If we can let it slide this one time, I'll make every future commit with conventional commits.

**Comment by saiichihashimoto** [comment]
> Hey @saiichihashimoto, so I've tried to do this, but I'm being told that Husky has a pre-rebase hook that catching and preventing me from doing so. Furthermore, it's also not a great idea to rebase pushed commits. If we can let it slide this one time, I'll make every future commit with conventional commits.

It's no problem, we can push this through. It just isn't going to deploy until the next commit that triggers a release, but I suspect that will be pretty soon.

**Review by saiichihashimoto — APPROVED** [review]

**Comment by cereallarceny** [comment]
pig

**Pull request merged**
